name: 'Issue tracking'
description: 'GitHub Action for adding a link to ticket on PR description from PR title"'
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  host:
    description: 'issue tracking host URL'
    required: true
  pathname:
    description: 'pathname to issuer',
    required: true
  title:
    description: 'Title of the tickets section in the PR description'
    required: false
  verify:
    description: 'Indicates weather the action should validate the PR title'
    required: false
  ignore_label:
    description: 'Label name, When label set, the action will skip verification'
    required: false
  milestone:
    description: 'Boolean value to indicate if milestone should be added if available from issue'
    required: false
  jira_username:
    description: 'JIRA username for authentication, required when milestone option is enabled'
    required: false
  jira_token:
    description: 'JIRA token for authentication, required when milestone option is enabled'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: external-link
  color: gray-dark
