name: 'Update ticket on PR description'
description: 'GitHub Action for adding a link to ticket on PR description from PR title"'
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  host:
    description: 'issue tracking host URL'
    required: true
  title:
    description: 'Title of the tickets secition in the PR description'
    required: false
  verify:
    description: 'Indicates weather the action should validate the PR title'
    required: false
  ignore_label:
    description: 'Label name, When label set, the action will skip verification'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: external-link
  color: gray-dark
