const VERIFY_DEFAULT_VALUE = false;
const IGNORE_LABEL_DEFAULT_VALUE = '-issuer';
const TITLE_DEFAULT_VALUE = '### Issuer';
const SEPARATOR  = ':';

module.exports = {
    IGNORE_LABEL_DEFAULT_VALUE,
    VERIFY_DEFAULT_VALUE,
    SEPARATOR,
    TITLE_DEFAULT_VALUE,
}
